version: '3.7'

services:

  http-cache-proxy:
    build: .
    image: flaviostutz/http-cache-proxy
    ports:
      - 8282:80
    environment:
      - PROXY_PASS_URL=http://localhost:8181/

  map-demos:
    image: flaviostutz/map-demos
    ports: 
      - 8181:80
    restart: always
    # environment:
    #   - GEOJSON_URL=http://localhost:8080/collections/tests/items
    #   - MAPBOX_VECTOR_TILE_URL=http://localhost:3000/tiles/tests/{z}/{x}/{y}.mvt?limit=100
